### ISSUE TITLE
shift-cmd-, doesn't work

### ISSUE THREAD

**Issue by wjordan213** [MartinPeverelli/erb-snippets#3]
I have to use packages -> erb-snippets -> erb tags to get the same effect

**Comment by MartinPeverelli** [comment]
@wjordan213 Atom updates to how key bindings work broke the selectors on this plugin.
I've published v0.4.2 which fixes your issue. However, I had to change the default keybinding, from cmd-shift-, to cmd-shift-.
Hope it helps! Thanks!
